---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: rook-nfs
  name: rook-nfs-{{ .Values.nfs.path }}
parameters:
  exportName: "{{ .Values.nfs.path }}"
  nfsServerName: "{{ .Values.nfs.server }}"
  nfsServerNamespace: "{{ .Values.nfs.namespace }}"
provisioner: rook.io/nfs-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
