self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
    - warp-ubuntu-latest-arm64-4x
    - warp-ubuntu-latest-x64-4x
    - warp-ubuntu-latest-arm64-16x
    - warp-ubuntu-latest-x64-16x
