// automatically generated by the FlatBuffers compiler, do not modify

package task

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RaftContext struct {
	_tab flatbuffers.Table
}

func GetRootAsRaftContext(buf []byte, offset flatbuffers.UOffsetT) *RaftContext {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RaftContext{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RaftContext) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RaftContext) Id() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RaftContext) MutateId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *RaftContext) Group() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RaftContext) MutateGroup(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *RaftContext) Addr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RaftContextStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RaftContextAddId(builder *flatbuffers.Builder, id uint64) {
	builder.PrependUint64Slot(0, id, 0)
}
func RaftContextAddGroup(builder *flatbuffers.Builder, group uint32) {
	builder.PrependUint32Slot(1, group, 0)
}
func RaftContextAddAddr(builder *flatbuffers.Builder, addr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(addr), 0)
}
func RaftContextEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
