version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - "8080"
      - "9080"
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ./out/0/p
        target: /posting
        read_only: false
    command: /gobin/dgraph alpha --my=alpha1:7080 --zero=zero1:5080 -p=/posting --logtostderr
      -v=2 --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha2:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha2
    labels:
      cluster: test
    ports:
      - "8080"
      - "9080"
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ./out/1/p
        target: /posting
        read_only: false
    command: /gobin/dgraph alpha --my=alpha2:7080 --zero=zero1:5080 -p=/posting --logtostderr
      -v=2 --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha3:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha3
    labels:
      cluster: test
    ports:
      - "8080"
      - "9080"
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ./out/2/p
        target: /posting
        read_only: false
    command: /gobin/dgraph alpha --my=alpha3:7080 --zero=zero1:5080 -p=/posting --logtostderr
      -v=2 --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
