version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - "5080"
      - "6080"
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: volume
        source: data
        target: /data
        read_only: false
    command:
      /gobin/dgraph zero --telemetry "reports=false; sentry=false;" --raft="idx=1" --my=zero1:5080
      --logtostderr -v=2 --bindall
volumes:
  data: {}
