run:
  tests: false

linters-settings:
  lll:
    line-length: 100

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - gas
    - gofmt
    - golint
    - gosimple
    - govet
    - lll
    - varcheck
    - unused
