run:
  skip-dirs:
  skip-files:

linters-settings:
  lll:
    line-length: 120
  staticcheck:
    checks:
      - all
      - '-SA1019' # it is okay to use math/rand at times.
  gosec:
    excludes: # these are not relevant for us right now
      - G101
      - G107
      - G108
      - G110
      - G112
      - G114
      - G201
      - G204
      - G306
      - G402
      - G404

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - gosec
    - gofmt
    - gosimple
    - govet
    - lll
    - unused
    - staticcheck
    - goimports
    - unconvert
