run:
  skip-dirs:
  skip-files:

linters-settings:
  lll:
    line-length: 120
  staticcheck:
    checks:
      - all
      - '-SA1019' # disable the rule

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
  # - gas
    - gofmt
    - gosimple
    - govet
    - lll
    - unused
    - staticcheck
    - goimports
