run:
  tests: false
  skip-dirs:
    - contrib
    - compose
    - graphql/bench
    - graphql/e2e
    - graphql/test
    - graphql/testdata
    - systest
    - t
  skip-files:
    - ".*test.go$"

linters-settings:
  lll:
    line-length: 120

linters:
  disable-all: true
  enable:
    #- errcheck
    #- ineffassign
    #- gas
    - gofmt
    #- golint
    - gosimple
    - govet
    - lll
    - varcheck
    - unused

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
        - golint
      text: "(const|var|type|method|func|struct field) .+ should be"
    - linters:
        - golint
      text: "(method parameter|func parameter|func result) .+ should be"
