run:
  tests: false

linters-settings:
  lll:
    line-length: 100

linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - gas
    - gofmt
    - golint
    - gosimple
    - govet
    - lll
    - varcheck
    - unused

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - linters:
        - golint
      text: "(const|var|type|method|func|struct field) .+ should be"
    - linters:
        - golint
      text: "(method parameter|func parameter|func result) .+ should be"
