FROM ubuntu:16.04 as builder

# Install GCC
RUN apt-get update && \
    apt-get install -y \
    gcc \
    cmake \
    wget

# Install Go
RUN wget https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.13.4.linux-amd64.tar.gz

# Configure go env vars
ENV GO111MODULE=on
ENV GOPATH=/gocode
ENV GOROOT=/usr/local/go
ENV PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# Prepare structure and change dir
RUN mkdir -p $GOPATH/src/github.com/ChainSafe/gossamer
WORKDIR $GOPATH/src/github.com/ChainSafe/gossamer

# Add go mod lock files and gossamer default config
COPY go.mod .
COPY go.sum .
COPY config.toml .

# Get go mods
RUN go mod download

# Copy gossamer sources
COPY . $GOPATH/src/github.com/ChainSafe/gossamer

# Build
RUN GOBIN=$GOPATH/src/github.com/ChainSafe/gossamer/build/bin go run scripts/ci.go install

# Create symlink
RUN ln -s $GOPATH/src/github.com/ChainSafe/gossamer/build/bin/gossamer /usr/local/gossamer

# Give permissions
RUN chmod +x $GOPATH/src/github.com/ChainSafe/gossamer/scripts/docker-entrypoint.sh

# Expose cmd and port
ENTRYPOINT ["/gocode/src/github.com/ChainSafe/gossamer/scripts/docker-entrypoint.sh"]
CMD ["/usr/local/gossamer"]
EXPOSE 7001
