#!/bin/bash

function run {
  go test $@ |\
		GREP_COLORS='mt=00;32' egrep --line-buffered --color=always '^ok\ .*|' |\
		GREP_COLORS='mt=01;32' egrep --line-buffered --color=always '^\?\ .*|' |\
		GREP_COLORS='mt=00;31' egrep --line-buffered --color=always '.*FAIL.*|'
}

echo
echo "Running tests. Ignoring vendor folder."
run "$(go list ./... | grep -v vendor | grep -v cmd)"

echo
echo "Running tests in cmd directory."
run "$(go list ./... | grep -v vendor | grep cmd) --args --debugmode"
