version: "3.5"
services:
  zero:
    image: dgraph/dgraph:latest
    container_name: zero1
    working_dir: /data/zero1
    ports:
      - 5180:5180
      - 6180:6180
    labels:
      cluster: test
      service: zero1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command: /gobin/dgraph zero -o 100 --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10 --jaeger.collector=http://jaeger:14268 --my=zero1:5180

  alpha:
    image: dgraph/dgraph:latest
    container_name: alpha1
    working_dir: /data/alpha1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    ports:
      - 8180:8180
      - 9180:9180
    labels:
      cluster: test
      service: alpha1
    command: /gobin/dgraph alpha --lru_mb=1024 --zero=zero1:5180 -o 100 --expose_trace --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=2 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 --jaeger.collector=http://jaeger:14268 --my=alpha1:7180

  graphql:
    image: dgraph/dgraph:latest
    container_name: graphql
    working_dir: /data/graphql
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    ports:
      - 9100:9100
    labels:
      cluster: test
      service: graphql
    command: /gobin/dgraph graphql --alpha alpha1:9180 --jaeger.collector=http://jaeger:14268 --v 3 --port 9100

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    working_dir: /working/jaeger
    environment:
    - SPAN_STORAGE_TYPE=badger
    ports:
    - 14268:14268
    - 16686:16686
    command: --badger.ephemeral=false --badger.directory-key /working/jaeger --badger.directory-value /working/jaeger

  zeroAdmin:
    image: dgraph/dgraph:latest
    container_name: zeroAdmin
    working_dir: /data/zeroAdmin
    ports:
      - 5280:5280
      - 6280:6280
    labels:
      cluster: admintest
      service: zeroAdmin
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command: /gobin/dgraph zero -o 200 --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10 --my=zeroAdmin:5280

  alphaAdmin:
    image: dgraph/dgraph:latest
    container_name: alphaAdmin
    working_dir: /data/alphaAdmin
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    ports:
      - 8280:8280
      - 9280:9280
    labels:
      cluster: admintest
      service: alphaAdmin
    command: /gobin/dgraph alpha --lru_mb=1024 --zero=zeroAdmin:5280 -o 200 --expose_trace --trace 1.0 --profile_mode block --block_rate 10 --logtostderr -v=2 --whitelist 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16 --my=alphaAdmin:7280

  graphqlAdmin:
    image: dgraph/dgraph:latest
    container_name: graphqlAdmin
    working_dir: /data/graphqlAdmin
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    ports:
      - 9200:9200
    restart: always
    labels:
      cluster: admintest
      service: graphqlAdmin
    command: /gobin/dgraph graphql --alpha alphaAdmin:9280 --v 3 --port 9200
