version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:local
    working_dir: /data/alpha1
    ports:
      - "8080"
      - "9080"
    volumes:
      - type: bind
        source: ${DGRAPH_BIN_PATH:-$GOPATH/bin}
        target: /gobin
        read_only: true
      - type: bind
        source: ./audit_dir/aa
        target: /audit_dir
      - type: bind
        source: ../../ee/enc/test-fixtures/enc-key
        target: /dgraph-enc/enc-key
        read_only: true
    command: /gobin/dgraph  ${COVERAGE_OUTPUT} alpha --raft="idx=1;group=1" --my=alpha1:7080 --zero=zero1:5080
      --logtostderr --audit "output=/audit_dir;encrypt-file=/dgraph-enc/enc-key" -v=2
      --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;"
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - "5080"
      - "6080"
    volumes:
      - type: bind
        source: ${DGRAPH_BIN_PATH:-$GOPATH/bin}
        target: /gobin
        read_only: true
      - type: bind
        source: ./audit_dir/za
        target: /audit_dir
      - type: bind
        source: ../../ee/enc/test-fixtures/enc-key
        target: /dgraph-enc/enc-key
        read_only: true
    command: /gobin/dgraph  ${COVERAGE_OUTPUT} zero --raft="idx=1;" --my=zero1:5080 --logtostderr -v=2 --bindall
      --audit "output=/audit_dir;encrypt-file=/dgraph-enc/enc-key"
volumes: {}
