package schemarules

import (
	. "github.com/vektah/gqlparser/ast"
	"github.com/vektah/gqlparser/gqlerror"
	. "github.com/vektah/gqlparser/validator"
)

func init() {
	AddSchRule("NoQueryMutationInInitialSchema", func(schema *Schema) *gqlerror.Error {
		if schema.Query != nil || schema.Mutation != nil {
			return &gqlerror.Error{
				Message: "Query/Mutation shouldn't be part of input schema." +
					"They are meant to be generated by Dgraph",
			}
		}

		return nil
	})
}
