version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    container_name: alpha1
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - 8180:8180
      - 9180:9180
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/alpha1
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph alpha -o 100 --my=alpha1:7180 --zero=zero1:5180
      --logtostderr -v=2 --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha1.crt --tls_key /dgraph-tls/client.alpha1.key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha2:
    image: dgraph/dgraph:latest
    container_name: alpha2
    working_dir: /data/alpha2
    labels:
      cluster: test
    ports:
      - 8280:8280
      - 9280:9280
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/alpha2
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph alpha -o 200 --my=alpha2:7280 --zero=zero1:5180
      --logtostderr -v=2 --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha2.crt --tls_key /dgraph-tls/client.alpha2.key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha3:
    image: dgraph/dgraph:latest
    container_name: alpha3
    working_dir: /data/alpha3
    labels:
      cluster: test
    ports:
      - 8380:8380
      - 9380:9380
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/alpha3
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph alpha -o 300 --my=alpha3:7380 --zero=zero1:5180
      --logtostderr -v=2 --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha3.crt --tls_key /dgraph-tls/client.alpha3.key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  zero1:
    image: dgraph/dgraph:latest
    container_name: zero1
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - 5180:5180
      - 6180:6180
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/zero1
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero -o 100 --idx=1 --replicas 3 --my=zero1:5180 --logtostderr
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero1.crt --tls_key /dgraph-tls/client.zero1.key
      -v=2 --bindall
  zero2:
    image: dgraph/dgraph:latest
    container_name: zero2
    working_dir: /data/zero2
    labels:
      cluster: test
    ports:
      - 5280:5280
      - 6280:6280
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/zero2
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero -o 200 --idx=2 --replicas 3 --my=zero2:5280 --logtostderr --peer zero1:5180
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero2.crt --tls_key /dgraph-tls/client.zero2.key
      -v=2 --bindall
  zero3:
    image: dgraph/dgraph:latest
    container_name: zero3
    working_dir: /data/zero3
    labels:
      cluster: test
    ports:
      - 5380:5380
      - 6380:6380
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/zero3
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero -o 300 --idx=3 --replicas 3 --my=zero3:5380 --logtostderr --peer zero1:5180
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero3.crt --tls_key /dgraph-tls/client.zero3.key
      -v=2 --bindall
volumes: {}
