version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
      - 8080
      - 9080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/alpha1
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph alpha --my=alpha1:7080 --zero=zero1:5080
      --logtostderr -v=2 --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha1.crt --tls_key /dgraph-tls/client.alpha1.key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha2:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha2
    labels:
      cluster: test
    ports:
      - 8080
      - 9080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/alpha2
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph alpha --my=alpha2:7080 --zero=zero1:5080
      --logtostderr -v=2 --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha2.crt --tls_key /dgraph-tls/client.alpha2.key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha3:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha3
    labels:
      cluster: test
    ports:
      - 8080
      - 9080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/alpha3
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph alpha --my=alpha3:7080 --zero=zero1:5080
      --logtostderr -v=2 --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha3.crt --tls_key /dgraph-tls/client.alpha3.key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
      - 5080
      - 6080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/zero1
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero --idx=1 --replicas 3 --my=zero1:5080 --logtostderr
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero1.crt --tls_key /dgraph-tls/client.zero1.key
      -v=2 --bindall
  zero2:
    image: dgraph/dgraph:latest
    working_dir: /data/zero2
    labels:
      cluster: test
    ports:
      - 5080
      - 6080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/zero2
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero --idx=2 --replicas 3 --my=zero2:5080 --logtostderr --peer zero1:5080
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero2.crt --tls_key /dgraph-tls/client.zero2.key
      -v=2 --bindall
  zero3:
    image: dgraph/dgraph:latest
    working_dir: /data/zero3
    labels:
      cluster: test
    ports:
      - 5080
      - 6080
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../tls/zero3
        target: /dgraph-tls
        read_only: true
    command: /gobin/dgraph zero --idx=3 --replicas 3 --my=zero3:5080 --logtostderr --peer zero1:5080
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero3.crt --tls_key /dgraph-tls/client.zero3.key
      -v=2 --bindall
volumes: {}
