/*
 * Copyright 2023 Dgraph Labs, Inc. and Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package audit

import (
	"bufio"
	"crypto/aes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func check(t *testing.T, err error) {
	if err != nil {
		t.Fatal(err)
	}
}

// we will truncate copy of encrypted audit log file
func copy(t *testing.T, src string, dst string) {
	// could also us io.CopyN but this is a small file
	data, err := os.ReadFile(src)
	check(t, err)
	err = os.WriteFile(dst, data, 0666)
	check(t, err)
}

func TestDecrypt(t *testing.T) {
	key, err := os.ReadFile("../enc/test-fixtures/enc-key")
	check(t, err)

	// encrypted audit logs generated by TestGenerateAuditLogForTestDecrypt in testutil/audit.go
	// we check this in because we want this test to be a unit test
	filePath := "testfiles/zero_audit_0_1.log.enc"
	copyPath := "testfiles/zero_audit_0_1.log.enc.copy"
	decryptedPath := "testfiles/zero_audit_0_1.log"

	// during test we will truncate copy of file
	copy(t, filePath, copyPath)
	defer os.RemoveAll(copyPath)

	file, err := os.OpenFile(copyPath, os.O_RDWR, 0666)
	check(t, err)
	defer func() {
		if err := file.Close(); err != nil {
			t.Fatal("error closing file")
		}
	}()

	stat, err := os.Stat(copyPath)
	check(t, err)
	sz := stat.Size() // get size of audit log

	outfile, err := os.OpenFile(decryptedPath,
		os.O_CREATE|os.O_WRONLY|os.O_TRUNC, os.ModePerm)
	check(t, err)
	defer func() {
		if err := outfile.Close(); err != nil {
			t.Fatal(err)
		}
	}()
	defer os.RemoveAll("testfiles/zero_audit_0_1.log")
	block, err := aes.NewCipher(key)
	check(t, err)

	zeroCmd := []string{"/removeNode", "/assign", "/moveTablet"}

	// size of audit log is 825 bytes
	for i := 0; i <= int(sz); i = i + 5 {
		switch {
		case i == 0:
			decrypt(file, outfile, block, sz)
			verifyLogs(t, decryptedPath, zeroCmd)
			// clear output file
			outfile.Truncate(0)
			outfile.Seek(0, 0)
		case 5 <= i && i <= 275:
			file.Truncate(sz - int64(i))
			decrypt(file, outfile, block, sz)
			verifyLogs(t, decryptedPath, zeroCmd[0:1])
			outfile.Truncate(0)
			outfile.Seek(0, 0)
		case 280 <= i && i <= 535:
			file.Truncate(sz - int64(i))
			decrypt(file, outfile, block, sz)
			verifyLogs(t, decryptedPath, zeroCmd[0:0])
			outfile.Truncate(0)
			outfile.Seek(0, 0)
		case 540 <= i:
			// at this point the output file will be empty
			file.Truncate(sz - int64(i))
			// verify that decrypt does not panic
			decrypt(file, outfile, block, sz)
			outfile.Truncate(0)
			outfile.Seek(0, 0)
		}

	}
}

func verifyLogs(t *testing.T, path string, cmds []string) {
	abs, err := filepath.Abs(path)
	require.Nil(t, err)
	f, err := os.Open(abs)
	require.Nil(t, err)

	type log struct {
		Msg string `json:"endpoint"`
	}
	logMap := make(map[string]bool)

	fileScanner := bufio.NewScanner(f)
	for fileScanner.Scan() {
		bytes := fileScanner.Bytes()
		l := new(log)
		_ = json.Unmarshal(bytes, l)
		logMap[l.Msg] = true
	}
	for _, m := range cmds {
		if !logMap[m] {
			fmt.Println("failed here")
			t.Fatalf("audit logs not present for command %s", m)
		}
	}
}
