version: "3.3"
services:
  nginx:
    image: nginx:1.19.1
    volumes:
      - "./public:/home/ubuntu/dgraph/wiki/public:ro"
      - "./nginx/docs-docker.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 80:80
