name: "📃 Documentation Request"
description: Suggest improvements, additions, or revisions to Dgraph documentation
title: "[Documentation]: <Title>"
labels: ["area/documentation", "status/triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue.
        If you think Dgraph's documentation at https://dgraph.io/docs/ is lacking, please explain it here.
  - type: textarea
    attributes:
      label: What version of Dgraph is the target?
      description: Is it latest? old?
      placeholder: |
        Type here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Documentation.
      description: Explain which part of the documents is lacking.
      placeholder: |
          Type here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information.
      description: Tell us anything else you think we should know.
