version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:local
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
    - 8080
    - 9080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./data/backups
      target: /backups
      read_only: false
    - type: bind
      source: ./acl-secret
      target: /secret/hmac
      read_only: true
    command: /gobin/dgraph  ${COVERAGE_OUTPUT} alpha --telemetry "reports=false; sentry=false;" --my=alpha1:7080 --zero=zero1:5080
      --logtostderr -v=2 --raft "idx=1; group=1" --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;"
      --acl "secret-file=/secret/hmac;"
    deploy:
      resources:
        limits:
          memory: 32G
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
    - 5080
    - 6080
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    command: /gobin/dgraph  ${COVERAGE_OUTPUT} zero --telemetry "reports=false; sentry=false;" --raft='idx=1' --my=zero1:5080 --logtostderr
      -v=2 --bindall
    deploy:
      resources:
        limits:
          memory: 32G
volumes: {}
