version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:local
    working_dir: /data/zero1
    ports:
      - 5080
      - 6080
    labels:
      cluster: test
      service: zero
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command:
      /gobin/dgraph  ${COVERAGE_OUTPUT} zero --telemetry "reports=false; sentry=false;"
      --my=zero1:5080  --raft="idx=1" --logtostderr -v=2 --bindall --expose_trace --profile_mode
      block --block_rate 10 --limit refill-interval=20s --limit uid-lease=50
  alpha1:
    image: dgraph/dgraph:local
    working_dir: /data/alpha1
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../../ee/acl/hmac-secret
        target: /dgraph-acl/hmac-secret
        read_only: true
      - type: bind
        source: ../../ee/enc/test-fixtures/enc-key
        target: /dgraph-enc/enc-key
        read_only: true
    ports:
      - 8080
      - 9080
    labels:
      cluster: test
      service: alpha
    command:
      /gobin/dgraph  ${COVERAGE_OUTPUT} alpha --telemetry "reports=false; sentry=false;"
      --encryption "key-file=/dgraph-enc/enc-key;" --my=alpha1:7080
      --zero=zero1:5080,zero2:5080,zero3:5080 --expose_trace --profile_mode block --block_rate 10
      --logtostderr -v=2 --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;" --acl
      "secret-file=/dgraph-acl/hmac-secret; access-ttl=20s;"
