apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-dgraph-io
  labels:
    app: dgraph-io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-dgraph-io
  labels:
    app: dgraph-io
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-dgraph-io
  labels:
    app: dgraph-io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-dgraph-io
subjects:
- kind: ServiceAccount
  name: prometheus-dgraph-io
  namespace: default
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alpha.dgraph-io
  labels:
    app: dgraph-io
    prometheus: dgraph-io
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      monitor: alpha-dgraph-io
  endpoints:
  - port: http-alpha
    path: /debug/prometheus_metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: zero-dgraph-io
  labels:
    app: dgraph-io
    prometheus: dgraph-io
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      monitor: zero.dgraph-io
  endpoints:
  - port: http-zero
    path: /debug/prometheus_metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: dgraph-io
  labels:
    app: prometheus
spec:
  serviceAccountName: prometheus-dgraph-io
  alerting:
    alertmanagers:
    - namespace: default
      name: alertmanager-dgraph-io
      port: web
  serviceMonitorSelector:
    matchLabels:
      app: dgraph-io
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      app: dgraph-io
      prometheus: dgraph-io
      role: alert-rules
  enableAdminAPI: false
