# -*- mode: ruby -*-
# vi: set ft=ruby :
hosts = File.readlines("./hosts").map { |ln| i,h= ln.split(/\s+/); [h,i] }.to_h
replicas = hosts.keys.select { |host| host.to_s.match /^zero\d+/ }.count
version = ENV['DGRAPH_VERSION'] || 'v20.07.0'

Vagrant.configure("2") do |config|
  hosts.each do |hostname, ipaddr|
    config.vm.define hostname do |node|
      node.vm.box = "generic/ubuntu1804"
      node.vm.hostname = "#{hostname}"
      node.vm.network "private_network", ip: ipaddr
      node.vm.synced_folder ".", "/vagrant"

      node.vm.provision "shell" do |shell|
        shell.path = "provision.sh"
        shell.args = [replicas]
        shell.env = { DGRAPH_VERSION: version }
        shell.privileged = true
      end
    end
  end
end
