canonifyURLs = true
languageCode = "en-us"
theme = "hugo-docs"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
noClasses = false

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

# set by build script: title, baseurl
title = "Dgraph GraphQL Documentation"
