version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:latest
    working_dir: /data/zero1
    ports:
      - 5080
      - 6080
    labels:
      cluster: test
      service: zero
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
    command: /gobin/dgraph zero --my=zero1:5080 --raft="idx=1" --logtostderr -v=2 --bindall --expose_trace --profile_mode block --block_rate 10

  alpha1:
    image: dgraph/dgraph:latest
    working_dir: /data/alpha1
    env_file:
        - ./minio.env
    volumes:
      - type: bind
        source: $GOPATH/bin
        target: /gobin
        read_only: true
      - type: bind
        source: ../../ee/acl/hmac-secret
        target: /dgraph-acl/hmac-secret
        read_only: true
    ports:
      - 8080
      - 9080
    labels:
      cluster: test
      service: alpha
    command: /gobin/dgraph alpha --my=alpha1:7080 --zero=zero1:5080,zero2:5080,zero3:5080 --expose_trace --profile_mode block --block_rate 10 --logtostderr -v=2 
      --security "whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16;"
      --acl "secret-file=/dgraph-acl/hmac-secret; access-ttl=20s;"
      --limit "shared-instance=true"

  minio:
    image: minio/minio:latest
    env_file:
      - ./minio.env
    working_dir: /data/minio
    ports:
      - 9001
    labels:
      cluster: test
    command: minio server /data/minio --address :9001
