version: "3.8"

#
# A simple compose file for running single zero and alpha
#
services:

  # Dgraph Zero controls the cluster
  zero:
    image: dgraph/dgraph:$DGRAPH_VERSION
    container_name: local_dgraph_zero
    volumes:
      - ~/local-dgraph-data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero:5080 --logtostderr -v=2 --telemetry sentry=false
    restart: unless-stopped
  # Dgraph Alpha hosts the graph and indexes
  alpha:
    image: dgraph/dgraph:$DGRAPH_VERSION
    container_name: local_dgraph_alpha
    volumes:
      - ~/local-dgraph-data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    command: >
      dgraph alpha --my=alpha:7080 --zero=zero:5080
        --security whitelist=0.0.0.0/0
        --logtostderr -v=2
        --telemetry sentry=false
    restart: unless-stopped

  # Watchtower is a third party tool that will restart a container if an updated image is found
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=5
      - WATCHTOWER_WARN_ON_HEAD_FAILURE=never
      - WATCHTOWER_NO_PULL=true
      - WATCHTOWER_NOTIFICATIONS_LEVEL=error
  # Loads busybox so that the hook to the dgraph container logs doesn't close
  keepalive:
    image: busybox
    container_name: keepalive
    command: >
      sh -c "trap : TERM INT; sleep infinity & wait"
