apiVersion: v1
kind: Service
metadata:
  name: {{ template "dgraph.zero.fullname" . }}
  labels:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    component: {{ .Values.zero.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.zero.service.type }}
  ports:
  - port: 5080
    targetPort: 5080
    name: zero-grpc
  - port: 6080
    targetPort: 6080
    name: zero-http
  selector:
    app: {{ template "dgraph.name" . }}
    chart: {{ template "dgraph.chart" . }}
    release: {{ .Release.Name }}
    component: {{ .Values.zero.name }}