version: "3.5"
services:
  zero1:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    container_name: zero1
    working_dir: /data/zero1
    ports:
      - 5080:5080
      - 6080:6080
    command: dgraph zero --my=zero1:5080 --replicas 1 --raft="idx=1;"

  alpha1:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    container_name: alpha1
    working_dir: /data/alpha1
    ports:
      - 8080:8080
      - 9080:9080
    command: dgraph alpha --my=alpha1:7080 --lru_mb=1024 --zero=zero1:5080 
      --security "whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1;"
    volumes:
      - type: volume
        source: nfsmount
        target: /data/backups
        volume:
          nocopy: true

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NFS_SERVER},rw,nolock,soft,nointr,nfsvers=4
      device: ":${NFS_PATH}"
