version: "3.5"
services:
  alpha1:
    image: dgraph/dgraph:latest
    container_name: alpha1
    working_dir: /data/alpha1
    labels:
      cluster: test
    ports:
    - 8180:8180
    - 9180:9180
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup
      read_only: false
    - type: bind
      source: ../tls/alpha1
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha -o 100 --my=alpha1:7180 --zero=zero1:5180
      --logtostderr -v=2 --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha1.crt --tls_key /dgraph-tls/client.alpha1.key
      --idx=1 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha2:
    image: dgraph/dgraph:latest
    container_name: alpha2
    working_dir: /data/alpha2
    depends_on:
    - alpha1
    labels:
      cluster: test
    ports:
    - 8182:8182
    - 9182:9182
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup
      read_only: false
    - type: bind
      source: ../tls/alpha2
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha -o 102 --my=alpha2:7182 --zero=zero1:5180 --logtostderr -v=2
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha2.crt --tls_key /dgraph-tls/client.alpha2.key
      --idx=2 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha3:
    image: dgraph/dgraph:latest
    container_name: alpha3
    working_dir: /data/alpha3
    depends_on:
    - alpha2
    labels:
      cluster: test
    ports:
    - 8183:8183
    - 9183:9183
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup
      read_only: false
    - type: bind
      source: ../tls/alpha3
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha -o 103 --my=alpha3:7183 --zero=zero1:5180 --logtostderr -v=2
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha3.crt --tls_key /dgraph-tls/client.alpha3.key
      --idx=3 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha4:
    image: dgraph/dgraph:latest
    container_name: alpha4
    working_dir: /data/alpha4
    depends_on:
    - alpha3
    labels:
      cluster: test
    ports:
    - 8184:8184
    - 9184:9184
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup
      read_only: false
    - type: bind
      source: ../tls/alpha4
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha -o 104 --my=alpha4:7184 --zero=zero1:5180 --logtostderr -v=2
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha4.crt --tls_key /dgraph-tls/client.alpha4.key
      --idx=4 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha5:
    image: dgraph/dgraph:latest
    container_name: alpha5
    working_dir: /data/alpha5
    depends_on:
    - alpha4
    labels:
      cluster: test
    ports:
    - 8185:8185
    - 9185:9185
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup
      read_only: false
    - type: bind
      source: ../tls/alpha5
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha -o 105 --my=alpha5:7185 --zero=zero1:5180 --logtostderr -v=2
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha5.crt --tls_key /dgraph-tls/client.alpha5.key
      --idx=5 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  alpha6:
    image: dgraph/dgraph:latest
    container_name: alpha6
    working_dir: /data/alpha6
    depends_on:
    - alpha5
    labels:
      cluster: test
    ports:
    - 8186:8186
    - 9186:9186
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ./keys
      target: /data/keys
      read_only: true
    - type: bind
      source: ./backup
      target: /data/backup
      read_only: false
    - type: bind
      source: ../tls/alpha6
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph alpha -o 106 --my=alpha6:7186 --zero=zero1:5180 --logtostderr -v=2
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.alpha6.crt --tls_key /dgraph-tls/client.alpha6.key
      --idx=6 --encryption_key_file /data/keys/enc_key
      --whitelist=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
  zero1:
    image: dgraph/dgraph:latest
    container_name: zero1
    working_dir: /data/zero1
    labels:
      cluster: test
    ports:
    - 5180:5180
    - 6180:6180
    volumes:
    - type: bind
      source: $GOPATH/bin
      target: /gobin
      read_only: true
    - type: bind
      source: ../tls/zero1
      target: /dgraph-tls
      read_only: true
    command: /gobin/dgraph zero -o 100 --idx=1 --my=zero1:5180 --replicas=3
      --tls_cacert /dgraph-tls/ca.crt --tls_node_cert /dgraph-tls/node.crt --tls_node_key /dgraph-tls/node.key
      --tls_internal_port_enabled=true --tls_cert /dgraph-tls/client.zero1.crt --tls_key /dgraph-tls/client.zero1.key --logtostderr
      -v=2 --bindall
volumes: {}
