version: "3.5"
volumes:
  prometheus-volume:
  grafana-volume:
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    pid: "host"
    volumes:
      - type: bind
        source: /
        target: /host
        read_only: true
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: volume
        source: prometheus-volume
        target: /prometheus
      - type: bind
        source: $GOPATH/src/github.com/dgraph-io/dgraph/dgraph/prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
     - "3000:3000"
    environment:
      # Skip login
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - type: volume
        source: grafana-volume
        target: /var/lib/grafana
