name: cd-dgraph
on: workflow_dispatch
jobs:
  dgraph-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install protobuf-compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Check protobuf
        run: |
          cd ./protos
          go mod tidy
          make regenerate
          git diff --exit-code -- .
      - name: Make Linux Build
        run: |
          #!/bin/bash
          # go settings
          export GOOS=linux
          export GOARCH=amd64
          # make dgraph binary
          make dgraph $(VERSION)
      - name: Make Dgraph Docker Image
        run: |
        make docker-image latest 
        make docker-image $(VERSION)
      - name: Make Dgraph Standalone Docker Image with Version
        run: |
        make standalone-docker-image latest
        make standalone-docker-image $(VERSION)
      - name: Push Images to DockerHub
        run: |
          docker login --username=$DOCKERHUB_USER_TEST --password=$DOCKERHUB_PASSWORD_TOKEN_TEST
          docker push dgraph/standalone:latest
          docker push dgraph/standalone:$(VERSION)
          docker push dgraph/dgraph:latest
          docker push dgraph/dgraph:$(VERSION)
