name: cd-dgraph
on: workflow_dispatch
jobs:
  dgraph-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: make dependency
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Check protobuf
        run: |
          cd ./protos
          go mod tidy
          make regenerate
          git diff --exit-code -- .
      - name: Set Dgraph Release Version
        run: |
          #!/bin/bash
          GIT_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          if [[ "$GIT_BRANCH_NAME" == *"release/"* ]]; 
          then
            echo "this is a release branch"
          else
            echo "this is NOT a release branch"
            exit 1
          fi
          DGRAPH_RELEASE_VERSION=$(git rev-parse --abbrev-ref HEAD | sed  's/release\///')
          echo "making a new release for "$DGRAPH_RELEASE_VERSION
          echo "DGRAPH_RELEASE_VERSION=$DGRAPH_RELEASE_VERSION" >> $GITHUB_ENV
      - name: Make Linux Build
        run: make dgraph DGRAPH_VERSION=${{ env.DGRAPH_RELEASE_VERSION }}
      - name: Make Dgraph Docker Image
        run: |
          make docker-image DGRAPH_VERSION=latest
          make docker-image DGRAPH_VERSION=${{ env.DGRAPH_RELEASE_VERSION }}
      - name: Make Dgraph Standalone Docker Image with Version
        run: |
          make docker-image-standalone DGRAPH_VERSION=latest
          make docker-image-standalone DGRAPH_VERSION=${{ env.DGRAPH_RELEASE_VERSION }}
      - name: Push Images to DockerHub
        run: |
          docker login --username=$DOCKERHUB_USER_TEST --password=$DOCKERHUB_PASSWORD_TOKEN_TEST
          docker push dgraph/standalone:latest
          docker push dgraph/standalone:${{ env.DGRAPH_RELEASE_VERSION }}
          docker push dgraph/dgraph:latest
          docker push dgraph/dgraph:${{ env.DGRAPH_RELEASE_VERSION }}
