name: ci-aqua-security-trivy-tests
on:
  pull_request:
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.vscode/**'
      - 'compose/**'
      - 'contrib/systemd/**'
      - 'licenses/**'
      - 'paper/**'
      - 'present/**'
      - 'RFC/**'
      - 'static/**'
      - 'wiki/**'
      - '**/**.dockerignore'
      - '**/**.gitignore'
      - '**/**.md'
      - '**/**.png'
      - '**/**.jpg'
      - '**/**.gif'
      - '**/**.ini'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - 'release/**'
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: trivy-tests
    if: github.event.pull_request.draft == false
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Build Docker image
        run: |
          make docker-image
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dgraph/dgraph:local'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
