name: Go Example
on: [pull_request]

permissions:
  contents: write
  deployments: write

jobs:
  dgraph-benchmark:
    name: Run Dgraph benchmarks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Dgraph
        uses: actions/checkout@v3
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install protobuf-compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Check protobuf
        run: |
          cd ./protos
          go mod tidy
          make regenerate
          git diff --exit-code -- .
      - name: Make Linux Build and Docker Image
        run: make docker-image
      - name: Clean Up Environment
        run: |
          #!/bin/bash
          # clean cache
          go clean -testcache
      - name: Run benchmark
        run: cd dgraph/systest/bench && go test -benchmem -run=^$ -bench ^BenchmarkBulkload | tee output.txt
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: dgraph/systest/bench/output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@anurags92'

      - name: Store benchmark result - separate results repo
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: 'go'
          output-file-path: dgraph/systest/bench/output.txt
          github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@anurags92'
          gh-repository: 'github.com/benchmark-action/github-action-benchmark-results'