name: ci-dgraph-load-tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
jobs:
  dgraph-load-tests:
    if: github.event.pull_request.draft == false
    runs-on: [self-hosted, x64]
    steps:
      - uses: actions/checkout@v3
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install protobuf-compiler
        run: sudo apt-get install -y protobuf-compiler
      - name: Check protobuf
        run: |
          cd ./protos
          go mod tidy
          make regenerate
          git diff --exit-code -- .
      - name: Make Docker Image
        run: make docker-image
      - name: Clean Up Environment
        run: |
          #!/bin/bash
          # clean cache
          go clean -testcache
          # build the test binary
          cd t; go build .
          # clean up docker containers before test execution
          ./t -r
      - name: Run Load Tests
        run: |
          #!/bin/bash
          # go env settings
          export GOPATH=~/go
          # run the load tests
          cd t
          ./t --suite=load
          # clean up docker containers after test execution
          ./t -r
          # sleep
          sleep 5
