name: ci-dgraph-upgrade-tests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - 'release/**'
jobs:
  dgraph-upgrade-tests:
    if: github.event.pull_request.draft == false
    runs-on: warp-ubuntu-latest-x64-16x 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVERSION }}
      - name: Make Linux Build and Docker Image
        run: make docker-image
      - name: Clean Up Environment
        run: |
          #!/bin/bash
          # clean cache
          go clean -testcache
      - name: Run Upgrade Tests
        run: |
          #!/bin/bash
          # go env settings
          export GOPATH=~/go
          export DGRAPH_UPGRADE_MAIN_ONLY=true
          # move the binary
          cp dgraph/dgraph ~/go/bin/dgraph
          # run the tests
          go test -v -timeout=120m -failfast -tags=upgrade ./...
          # clean up docker containers after test execution
          go clean -testcache
          # sleep
          sleep 5
