name: ci-golang-lint
on:
  pull_request:
    paths:
      - '**/*.go'
      - '**/go.mod'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - 'release/**'
jobs:
  golang-lint:
    if: github.event.pull_request.draft == false
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: golang-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          only-new-issues: true
          args: --timeout=10m
          skip-cache: true
