name: ci-golang-lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - '.github/CODEOWNERS'
      - '.vscode/**'
      - 'compose/**'
      - 'contrib/systemd/**'
      - 'licenses/**'
      - 'paper/**'
      - 'present/**'
      - 'RFC/**'
      - 'static/**'
      - 'wiki/**'
      - '**/**.dockerignore'
      - '**/**.gitignore'
      - '**/**.md'
      - '**/**.png'
      - '**/**.jpg'
      - '**/**.gif'
      - '**/**.ini'
    branches:
      - main
      - 'release/**'
jobs:
  golang-lint:
    if: github.event.pull_request.draft == false
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Go Version
        run: |
          #!/bin/bash
          GOVERSION=$({ [ -f .go-version ] && cat .go-version; })
          echo "GOVERSION=$GOVERSION" >> $GITHUB_ENV
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOVERSION }}
      - name: golang-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          only-new-issues: true
          args: --timeout=10m
          skip-pkg-cache: true
          skip-build-cache: true
