name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
      - 'release/**'
  pull_request:
    branches: 
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Make OSS Build
      run: make oss
    - name: Make macOS build
      run: make GOOS=darwin dgraph
    - name: Make Windows Build
      run: make GOOS=windows dgraph
    - name: Make Linux Build 
      run: make GOOS=linux dgraph
    - name: Check protobuf
      run: echo "test"
        
