name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - 'release/**'
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        env:
          # prevent OOM
          GOGC: 10
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.36
          only-new-issues: true
          args: --timeout=10m
          skip-go-installation: true
