name: Labeler
on:
  pull_request:
    branches:
      - master
      - 'release/**'
    types: [opened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
