provisionDataStore:
  cassandra: true
storage:
  type: cassandra
  cassandra:
    user: cassandrauser
    usePassword: true
    ## CHANGE THIS BEFORE DEPLOYING!!!
    password: CHANGEME
    
## The settings under cassandra can be found here:
##   https://github.com/helm/charts/tree/master/incubator/cassandra
cassandra:
  persistence:
    enabled: true
  image:
    repo: cassandra
    tag: 3.11.8

agent:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
collector:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
query:
  ## Optional Monitoring for Prometheus
  serviceMonitor:
    enabled: false
    additionalLabels: {release:  prometheus}
